[package]
name = "sir-simple-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evm-glue.workspace = true
eth-ir-data.workspace = true
sir-analyses.workspace = true
